# Список пользователей
GET http://127.0.0.1:8000/api/users/

###

#  Регистрация пользователя
POST http://127.0.0.1:8000/api/users/
{
    "username": "admin",
    "email": "admin@mail.ru",
    "first_name": "admin",
    "last_name": "admin",
    "password": "0000"
}

###

#Профиль пользователя (указать в конце ID пользователя)
GET http://127.0.0.1:8000/api/users/1/

###

# Текущий пользователь
GET http://127.0.0.1:8000/api/users/me/

###

# Изменение пароля
POST http://127.0.0.1:8000/api/users/set_password/

{
    "new_password": "ghghghghghghgh",
    "current_password": "0000"
}
###
# Получить токен авторизации
POST http://127.0.0.1:8000/api/auth/token/login/

{
    "username": "admin",
    "email": "admin@mail.ru",
    "first_name": "admin",
    "last_name": "admin",
    "password": "0000"
}

###
# Удаление токена
POST http://127.0.0.1:8000/api/auth/token/logout/


###
DELETE http://127.0.0.1:8000/api/users/1/
{
    "current_password":"8092354167b"
}

# ТЕГИ ----------------------------------------

###
# Список тегов
GET http://127.0.0.1:8000/api/tags/

###
# Получение тега (в конце нужно указать ID)
GET http://127.0.0.1:8000/api/tags/1/


###
# РЕЦЕПТЫ ----------------------------------------

# Список рецептов
GET http://127.0.0.1:8000/api/recipes/
 
 
 Responses
{
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 3,
            "author": {
                "id": 2,
                "username": "admin2",
                "email": "emarcoder@gmail.com",
                "first_name": "Artur",
                "last_name": "odin",
                "is_subscribed": true
            },
            "name": "айран",
            "image": "http://activate.adobe.com:5000/media/recipes/image/Screenshot_11_Kq91eqG.jpg",
            "text": "hjkjk",
            "ingredients": [
                {
                    "id": 2,
                    "name": "абрикосовое пюре",
                    "measurement_unit": "г",
                    "amount": 1
                },
                {
                    "id": 4,
                    "name": "абрикосовый сок",
                    "measurement_unit": "стакан",
                    "amount": 1
                }
            ],
            "tags": [
                {
                    "id": 1,
                    "name": "Ужин",
                    "color": "#A85BFF",
                    "slug": "Diner"
                }
            ],
            "cooking_time": 12,
            "is_in_shopping_cart": false,
            "is_favorited": false
        },
        {
            "id": 2,
            "author": {
                "id": 1,
                "username": "admin",
                "email": "admin@mail.ru",
                "first_name": "admin",
                "last_name": "admin",
                "is_subscribed": false
            },
            "name": "Салат",
            "image": "http://activate.adobe.com:5000/media/recipes/image/Screenshot_11.jpg",
            "text": "пвапвап",
            "ingredients": [
                {
                    "id": 1,
                    "name": "абрикосовое варенье",
                    "measurement_unit": "г",
                    "amount": 1
                },
                {
                    "id": 7,
                    "name": "айран",
                    "measurement_unit": "г",
                    "amount": 1
                },
                {
                    "id": 9,
                    "name": "алыча",
                    "measurement_unit": "г",
                    "amount": 1
                }
            ],
            "tags": [
                {
                    "id": 3,
                    "name": "Завтрак",
                    "color": "#FF3C0F",
                    "slug": "Breakfast"
                }
            ],
            "cooking_time": 2,
            "is_in_shopping_cart": false,
            "is_favorited": true
        }
    ]
}


###

# Создание рецепта
POST http://127.0.0.1:8000/api/recipes/

{
  "ingredients": [
    {
      "id": 1123,
      "amount": 10
    }
  ],
  "tags": [
    1,
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}

###

# Получение рецепта (в конце нужно указать ID)
GET http://127.0.0.1:8000/api/recipes/1/

###

# Обновление рецепта (в конце нужно указать ID)
PATCH  http://127.0.0.1:8000/api/recipes/1/

{
  "ingredients": [
    {
      "id": 1123,
      "amount": 10
    }
  ],
  "tags": [
    1,
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "string",
  "text": "string",
  "cooking_time": 1
}

####

# Удаление рецепта (в конце нужно указать ID)
DELETE http://127.0.0.1:8000/api/recipes/1/

###

# Список покупок -----------------------------------

# Скачать список покупок
GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/

###

# Добавить рецепт в список покупок (Указать ID)
POST http://127.0.0.1:8000/api/recipes/1/shopping_cart/

{
  "id": 0,
  "name": "string",
  "image": "http://foodgram.example.org/media/recipes/images/image.jpeg",
  "cooking_time": 1
}

###

# Удалить рецепт из списка покупок (Указать ID)
DELETE http://127.0.0.1:8000/api/recipes/1/shopping_cart/

###

# Избранное -----------------------------------------

# Добавить рецепт в избранное (Указать ID)
POST http://127.0.0.1:8000/api/recipes/1/favorite/

{
  "id": 0,
  "name": "string",
  "image": "http://foodgram.example.org/media/recipes/images/image.jpeg",
  "cooking_time": 1
}

### 

# Удалить рецепт из избранного (Указать ID)
DELETE http://127.0.0.1:8000/api/recipes/1/favorite/

###

# Подписки ----------------------------------------

# Мои подписки
GET http://127.0.0.1:8000/api/users/subscriptions/

###

# Подписаться на пользователя (Указать ID)
POST http://127.0.0.1:8000/api/users/1/subscribe/

{
  "email": "user@example.com",
  "id": 0,
  "username": "string",
  "first_name": "Вася",
  "last_name": "Пупкин",
  "is_subscribed": true,
  "recipes": [
    {
      "id": 0,
      "name": "string",
      "image": "http://foodgram.example.org/media/recipes/images/image.jpeg",
      "cooking_time": 1
    }
  ],
  "recipes_count": 0
}

###

# Отписаться от пользователя (Указать ID)
DELETE http://127.0.0.1:8000/api/users/1/subscribe/

###

# Ингредиенты ------------------------------------

# Список ингредиентов
GET http://127.0.0.1:8000/api/ingredients/

###

# Получение ингредиента (Указать ID)
GET http://127.0.0.1:8000/api/ingredients/1/