version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env

  backend:
    image: emarpoint/foodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/backend/static/
      - media_value:/app/backend/media/
    env_file:
      - ./.env


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - result_build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend


volumes:
  result_build:
  postgres_data:
  static_value:
  media_value: