# Generated by Django 2.2.19 on 2022-06-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username', 'email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
